//
// Created by paul on 19/07/23.
//

#ifndef PARTICLESYSTEM_CONSTANTS_H
#define PARTICLESYSTEM_CONSTANTS_H

const int WINDOW_WIDTH = 1100;
const int WINDOW_HEIGHT = 650;

#endif //PARTICLESYSTEM_CONSTANTS_H
